services:
  python:
    image: knapsack-api-python
    build: ./knapsack-problem-python
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - ./knapsack-problem-python:/code
  php:
    image: knapsack-api-php
    build: ./knapsack-problem-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./knapsack-problem-php:/var/www
    networks:
      - knapsack_problem_network
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "4040:80"
    volumes:
      - ./knapsack-problem-php:/var/www
      - ./knapsack-problem-php/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - knapsack_problem_network
    depends_on:
      - php
  node:
    image: knapsack-api-node
    build: ./knapsack-problem-node
    restart: unless-stopped
    ports:
      - "7070:8080"
    volumes:
      - ./knapsack-problem-node:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
  java:
    image: knapsack-api-java
    build: ./knapsack-problem-java
    restart: unless-stopped
    ports:
      - "6060:8080"
    volumes:
      - ./knapsack-problem-java:/app
    environment:
      SERVER_PORT: "8080"
  golang:
    build: ./knapsack-problem-golang
    image: knapsack-problem-golang
    ports:
      - "3030:8080" # Web Server
    volumes:
      - ./knapsack-problem-golang:/app
    environment:
      PORT: "8080"

networks:
  knapsack_problem_network:
